# Generated by Django 3.2.20 on 2023-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='pfp',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
