# Generated by Django 3.2.20 on 2023-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_friend_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='pfp',
        ),
        migrations.AddField(
            model_name='friend',
            name='upload',
            field=models.ImageField(default='NULL', upload_to='uploads/'),
        ),
    ]
