# Generated by Django 3.2.20 on 2023-11-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231112_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='upload',
            field=models.ImageField(default='NULL', upload_to='media/'),
        ),
    ]
